version: "3"

services:

  db:
    image: mysql
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: devdb

  web:
    build: .
    restart: on-failure
    depends_on:
      - db
    ports:
      - "8081:8081"

      
      
      
      
