# Server
server:
  port: 8081


#Mailing
spring:

   mail:
     host: smtp.gmail.com
     port: 587
     username: e-mail
     password: password
     properties:
       mail.smtp:
         auth: true
         starttls.enable: true


   # DataBase
   dataSource:
     url: jdbc:mysql://0.0.0.0:3306/devdb
     username: root
     password: password
   jpa:
     database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
     database: mysql
     show-sql: true
     hibernate:
       ddl-auto: update

---
# Mailing
spring:

  profiles:
    active: container

  mail:
    host: smtp.gmail.com
    port: 587
    username: e-mail
    password: password
    properties:
      mail.smtp:
        auth: true
        starttls.enable: true

  # DataBase
  dataSource:
    url: jdbc:mysql://db:3306/devdb
    username: root
    password: password
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update

